### ISSUE TITLE
Request detection result files about cryptographic misuse experiments

### ISSUE THREAD

**Issue by panoob** [xinjin95/IoTSpotter#1]
Dear authors,

I am a student interested in your paper (Understanding IoT Security from a Market-Scale Perspective), from which I learned a lot.

In particular, I am interested in Section 6 part, Cryptographic API misuse analysis. I would appreciate it if you would share the detailed results of the experiment (detection results files, timeout setting, runs in a single process or multiple processes)? I also noticed that non-Iot apps are not listed in the repo, and it would be great if this could also be listed for further research.

**Comment by kaflekaushal** [comment]
@panoob We set the timeout at 2100s (35min), and set the JVM allocated memory at 4GB for the experiments (`java -Xmx4096M`). The rest of the settings were defaults of the tools. 
If you need access to the intermediary results, please reach out to us via email. Thanks.

**Comment by xinjin95** [comment]
Hi @panoob, regarding non-IoT apps, I have uploaded the list of all apps (IoT + non-IoT) to [drive](https://drive.google.com/file/d/1LMmSO6ovyUR4LT-QKsVXaJGcO74l-HkP/view?usp=sharing). To obtain non-IoT apps, you can simply diff this file with the IoT app [list](https://github.com/xinjin95/IoTSpotter/blob/main/data/apk_androzoo_sha256/shared_sha256_androzoo.csv).

**Comment by panoob** [comment]
Cool, Thanks a lot!
